#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The hook URL is a credential. Nothing here writes it to disk, so ENV_FILE is
# pointed at a non-file: _existing() then always returns empty and write_env is
# never called.
ENV_FILE="/dev/null"

# gh reads GH_REPO, so the library's bare `gh secret set` targets the app repo
# rather than whatever directory this is run from.
APP_REPO="kauredo/basketball-video-analyzer"
export GH_REPO="$APP_REPO"

VERCEL_TEAM="kauredos-projects"
VERCEL_PROJECT="basketball-video-analyzer-website"
HOOK_SETTINGS_URL="https://vercel.com/${VERCEL_TEAM}/${VERCEL_PROJECT}/settings/git"

banner "Connect releases to the website rebuild"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the two tools this needs before you touch a browser."
if ! command -v gh >/dev/null 2>&1; then
  warn "the GitHub CLI (gh) is not installed."
  note "Install it with: brew install gh"
  note "Then re-run this wizard."
  exit 1
fi
printf '  %s✓%s gh is installed\n' "$GREEN" "$RESET"

if ! gh auth status >/dev/null 2>&1; then
  warn "gh is installed but not authenticated."
  note "Run: gh auth login"
  note "Then re-run this wizard."
  exit 1
fi
printf '  %s✓%s gh is authenticated\n' "$GREEN" "$RESET"

if gh repo view "$APP_REPO" >/dev/null 2>&1; then
  printf '  %s✓%s you can reach %s\n' "$GREEN" "$RESET" "$APP_REPO"
else
  warn "cannot reach $APP_REPO with your current gh login."
  note "Check with: gh auth status"
  exit 1
fi

if gh secret list --repo "$APP_REPO" 2>/dev/null | grep -q '^WEBSITE_DEPLOY_HOOK'; then
  note "WEBSITE_DEPLOY_HOOK already exists on $APP_REPO."
  if ! confirm "Replace it with a new hook URL?"; then
    say "Nothing to do. Exiting."
    exit 0
  fi
fi
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Why this exists"
say "The marketing site is a static build. It reads the app's latest release"
say "from the GitHub API at build time, then freezes that number until someone"
say "rebuilds it."
say ""
say "Nothing rebuilt it after v1.7.0, so the download button advertised 1.6.0"
say "while 1.7.2 was current. Coaches were downloading the build from before"
say "the Windows startup fix and before the auto-update repair, which is the"
say "one that would have let them update out of it."
say ""
say "After this wizard, publishing a release also pings the site to rebuild."
note "Merging the website PR fixes today's stale number on its own."
note "This hook is what stops it drifting again after the next release."
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the deploy hook in Vercel"
say "A deploy hook is a URL. POST to it and Vercel rebuilds the site."
open_url "$HOOK_SETTINGS_URL"
step "The Git settings page for '$VERCEL_PROJECT' should be open."
step "Scroll to the 'Deploy Hooks' section, near the bottom."
step "Name it:   release-rebuild"
step "Branch:    main"
step "Click 'Create Hook'."
step "Vercel shows the URL once. Copy it now."
say ""
note "It looks like https://api.vercel.com/v1/integrations/deploy/prj_.../<token>"
warn "Treat it as a password: anyone with it can trigger a deploy."
pause "Copied it? Press Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Store it as a GitHub secret"
say "The paste below is hidden, and the value goes to gh on stdin rather than"
say "as an argument, so it stays out of your shell history and scrollback."
say ""
ask_secret DEPLOY_HOOK "Paste the deploy hook URL:"

if [[ -z "${DEPLOY_HOOK:-}" ]]; then
  warn "nothing pasted. Re-run when you have the URL."
  exit 1
fi
case "$DEPLOY_HOOK" in
  https://api.vercel.com/v*/integrations/deploy/*) : ;;
  *)
    warn "that does not look like a Vercel deploy hook URL."
    note "Expected it to start with https://api.vercel.com/v1/integrations/deploy/"
    confirm "Use it anyway?" || exit 1
    ;;
esac

set_secret WEBSITE_DEPLOY_HOOK "$DEPLOY_HOOK"

say ""
step "Confirming it landed:"
if gh secret list --repo "$APP_REPO" | grep -E '^WEBSITE_DEPLOY_HOOK'; then
  printf '  %s✓%s the release workflow can now see it\n' "$GREEN" "$RESET"
else
  warn "the secret is not listed. Set it by hand:"
  note "  gh secret set WEBSITE_DEPLOY_HOOK --repo $APP_REPO"
  SKIPPED+=("WEBSITE_DEPLOY_HOOK on $APP_REPO")
fi
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Test it, optionally"
say "This POSTs to the hook once. Vercel starts one real production deploy of"
say "the marketing site, which is harmless: it rebuilds what is already there."
say ""
if confirm "Fire a test deploy now?"; then
  say ""
  if curl -fsS -X POST "$DEPLOY_HOOK" >/dev/null 2>&1; then
    printf '  %s✓%s Vercel accepted the request\n' "$GREEN" "$RESET"
    say ""
    step "Watch it build:"
    open_url "https://vercel.com/${VERCEL_TEAM}/${VERCEL_PROJECT}/deployments"
    note "A deployment dated just now should appear within a few seconds."
  else
    warn "the POST failed. The hook may be wrong, or revoked."
    note "Re-run this wizard and paste the URL again."
    SKIPPED+=("verify the deploy hook actually fires")
  fi
else
  note "Skipped. The next release will exercise it."
fi

unset DEPLOY_HOOK

finish
say "What happens now:"
note "  Push a v* tag on $APP_REPO. After the release publishes, the last step"
note "  of .github/workflows/release.yml POSTs to this hook and the site"
note "  rebuilds, picking up the new version on the download button."
say ""
note "The step is guarded on the secret, so a fork without it just skips."
printf '\n'
